version: '3.8'

services:
  web:
    image: shadowx01/plivoapi:v2.6.linux
    entrypoint: ["/app/entrypoint.sh"]
    #command: ["gunicorn", "messageService.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True 

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword

volumes:
  postgres_data:
